//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDT28.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLdienthoaiEntities : DbContext
    {
        public QLdienthoaiEntities()
            : base("name=QLdienthoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chitietdonhang> Chitietdonhangs { get; set; }
        public DbSet<Donhang> Donhangs { get; set; }
        public DbSet<Hangsanxuat> Hangsanxuats { get; set; }
        public DbSet<Hedieuhanh> Hedieuhanhs { get; set; }
        public DbSet<Nguoidung> Nguoidungs { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<Sanpham> Sanphams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
